{% set name = "pyplaces" %}
{% set version = "0.4.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyplaces-{{ version }}.tar.gz
  sha256: 437b1315384162423fa9908cbcb8594b29ec5f2b1ae440aaa724db4c6eb079d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - geopandas >=1.0.1,<2
    - shapely >=2.0.7,<3
    - pyproj >=3.7.1,<4
    - numpy >=2.2.4,<3
    - osmnx >=2.0.2,<3
    - typing_extensions
    - sentence-transformers <=4.1.0
    - pyarrow <=20.0.0
    - ipywidgets
    - python-duckdb

test:
  imports:
    - pyplaces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyplaces.readthedocs.io/en/latest/
  summary: pyplaces is a package used to easily read places data in remote storage from an address, place or bounding box.
  dev_url: https://github.com/tbanken/pyplaces
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tbanken
