{% set name = "pyplaces" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyplaces-{{ version }}.tar.gz
  sha256: d21ebf432615963b252e9c97da996582fc04b1f2f1bec80de5e48c18e2225845

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyarrow >=19.0.1,<20
    - geopandas >=1.0.1,<2
    - shapely >=2.0.7,<3
    - pyproj >=3.7.1,<4
    - numpy >=2.2.4,<3
    - osmnx >=2.0.2,<3
    - typing_extensions

test:
  imports:
    - pyplaces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tbanken/pyplaces
  summary: Pyplaces is a Python package that allows you to easily read places and other open source spatial data from a known address, place, or just a bounding box.
  dev_url: https://github.com/tbanken/pyplaces
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tbanken
