{% set name = "pyplaces" %}
{% set version = "0.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyplaces-{{ version }}.tar.gz
  sha256: a2a16f079f611cc7a8604285ed88431c681525b49200bd0e1afad5011c753c0f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - pyarrow >=19.0.1,<20
    - geopandas >=1.0.1,<2
    - shapely >=2.0.7,<3
    - pyproj >=3.7.1,<4
    - numpy >=2.2.4,<3
    - osmnx >=2.0.2,<3
    - typing_extensions
    - sentence-transformers
    - ipywidgets

test:
  imports:
    - pyplaces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyplaces.readthedocs.io/en/latest/
  summary: pyplaces is a package used to easily read places data in remote storage from an address, place or bounding box.
  dev_url: https://github.com/tbanken/pyplaces
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tbanken
